spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partitions?createDatabaseIfNotExist=true
    username: root
    password: 452678149
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: validate

flyway:
  enabled: true
  check-location: true
  locations: classpath:db/migration
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  sqlMigrationSeparator: __
  baseline-on-migrate: true
  validateOnMigrate: true
  baselineVersion: 0.9
  #use below property to allow placeholders in db queries.
  placeholder-replacement: false
  table: schema_version_partitions
  baselineOnMigrate: true